//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiffCreate.RVS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edc.usgs.gov", ConfigurationName="RVS.RequestValidationService")]
    public interface RequestValidationService {
        
        // CODEGEN: Generating message contract since element name requestInfoXml from namespace http://edc.usgs.gov is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiffCreate.RVS.processAOIResponse processAOI(DiffCreate.RVS.processAOIRequest request);
        
        // CODEGEN: Generating message contract since element name requestInfoXml from namespace http://edc.usgs.gov is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiffCreate.RVS.processAOI2Response processAOI2(DiffCreate.RVS.processAOI2Request request);
        
        // CODEGEN: Generating message contract since element name requestInfoXml from namespace http://edc.usgs.gov is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiffCreate.RVS.getTiledDataDirectURLsResponse getTiledDataDirectURLs(DiffCreate.RVS.getTiledDataDirectURLsRequest request);
        
        // CODEGEN: Generating message contract since element name requestInfoXml from namespace http://edc.usgs.gov is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiffCreate.RVS.getTiledDataDirectURLs2Response getTiledDataDirectURLs2(DiffCreate.RVS.getTiledDataDirectURLs2Request request);
        
        // CODEGEN: Generating message contract since element name requestInfoXml from namespace http://edc.usgs.gov is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DiffCreate.RVS.validateChunksResponse validateChunks(DiffCreate.RVS.validateChunksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processAOIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processAOI", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.processAOIRequestBody Body;
        
        public processAOIRequest() {
        }
        
        public processAOIRequest(DiffCreate.RVS.processAOIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class processAOIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestInfoXml;
        
        public processAOIRequestBody() {
        }
        
        public processAOIRequestBody(string requestInfoXml) {
            this.requestInfoXml = requestInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processAOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processAOIResponse", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.processAOIResponseBody Body;
        
        public processAOIResponse() {
        }
        
        public processAOIResponse(DiffCreate.RVS.processAOIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class processAOIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processAOIReturn;
        
        public processAOIResponseBody() {
        }
        
        public processAOIResponseBody(string processAOIReturn) {
            this.processAOIReturn = processAOIReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processAOI2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processAOI2", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.processAOI2RequestBody Body;
        
        public processAOI2Request() {
        }
        
        public processAOI2Request(DiffCreate.RVS.processAOI2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class processAOI2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestInfoXml;
        
        public processAOI2RequestBody() {
        }
        
        public processAOI2RequestBody(string requestInfoXml) {
            this.requestInfoXml = requestInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processAOI2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processAOI2Response", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.processAOI2ResponseBody Body;
        
        public processAOI2Response() {
        }
        
        public processAOI2Response(DiffCreate.RVS.processAOI2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class processAOI2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processAOI2Return;
        
        public processAOI2ResponseBody() {
        }
        
        public processAOI2ResponseBody(string processAOI2Return) {
            this.processAOI2Return = processAOI2Return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiledDataDirectURLsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiledDataDirectURLs", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.getTiledDataDirectURLsRequestBody Body;
        
        public getTiledDataDirectURLsRequest() {
        }
        
        public getTiledDataDirectURLsRequest(DiffCreate.RVS.getTiledDataDirectURLsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class getTiledDataDirectURLsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestInfoXml;
        
        public getTiledDataDirectURLsRequestBody() {
        }
        
        public getTiledDataDirectURLsRequestBody(string requestInfoXml) {
            this.requestInfoXml = requestInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiledDataDirectURLsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiledDataDirectURLsResponse", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.getTiledDataDirectURLsResponseBody Body;
        
        public getTiledDataDirectURLsResponse() {
        }
        
        public getTiledDataDirectURLsResponse(DiffCreate.RVS.getTiledDataDirectURLsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class getTiledDataDirectURLsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTiledDataDirectURLsReturn;
        
        public getTiledDataDirectURLsResponseBody() {
        }
        
        public getTiledDataDirectURLsResponseBody(string getTiledDataDirectURLsReturn) {
            this.getTiledDataDirectURLsReturn = getTiledDataDirectURLsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiledDataDirectURLs2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiledDataDirectURLs2", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.getTiledDataDirectURLs2RequestBody Body;
        
        public getTiledDataDirectURLs2Request() {
        }
        
        public getTiledDataDirectURLs2Request(DiffCreate.RVS.getTiledDataDirectURLs2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class getTiledDataDirectURLs2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestInfoXml;
        
        public getTiledDataDirectURLs2RequestBody() {
        }
        
        public getTiledDataDirectURLs2RequestBody(string requestInfoXml) {
            this.requestInfoXml = requestInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiledDataDirectURLs2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiledDataDirectURLs2Response", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.getTiledDataDirectURLs2ResponseBody Body;
        
        public getTiledDataDirectURLs2Response() {
        }
        
        public getTiledDataDirectURLs2Response(DiffCreate.RVS.getTiledDataDirectURLs2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class getTiledDataDirectURLs2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTiledDataDirectURLs2Return;
        
        public getTiledDataDirectURLs2ResponseBody() {
        }
        
        public getTiledDataDirectURLs2ResponseBody(string getTiledDataDirectURLs2Return) {
            this.getTiledDataDirectURLs2Return = getTiledDataDirectURLs2Return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateChunksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateChunks", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.validateChunksRequestBody Body;
        
        public validateChunksRequest() {
        }
        
        public validateChunksRequest(DiffCreate.RVS.validateChunksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class validateChunksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestInfoXml;
        
        public validateChunksRequestBody() {
        }
        
        public validateChunksRequestBody(string requestInfoXml) {
            this.requestInfoXml = requestInfoXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateChunksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateChunksResponse", Namespace="http://edc.usgs.gov", Order=0)]
        public DiffCreate.RVS.validateChunksResponseBody Body;
        
        public validateChunksResponse() {
        }
        
        public validateChunksResponse(DiffCreate.RVS.validateChunksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://edc.usgs.gov")]
    public partial class validateChunksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validateChunksReturn;
        
        public validateChunksResponseBody() {
        }
        
        public validateChunksResponseBody(string validateChunksReturn) {
            this.validateChunksReturn = validateChunksReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RequestValidationServiceChannel : DiffCreate.RVS.RequestValidationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestValidationServiceClient : System.ServiceModel.ClientBase<DiffCreate.RVS.RequestValidationService>, DiffCreate.RVS.RequestValidationService {
        
        public RequestValidationServiceClient() {
        }
        
        public RequestValidationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestValidationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestValidationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestValidationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiffCreate.RVS.processAOIResponse DiffCreate.RVS.RequestValidationService.processAOI(DiffCreate.RVS.processAOIRequest request) {
            return base.Channel.processAOI(request);
        }
        
        public string processAOI(string requestInfoXml) {
            DiffCreate.RVS.processAOIRequest inValue = new DiffCreate.RVS.processAOIRequest();
            inValue.Body = new DiffCreate.RVS.processAOIRequestBody();
            inValue.Body.requestInfoXml = requestInfoXml;
            DiffCreate.RVS.processAOIResponse retVal = ((DiffCreate.RVS.RequestValidationService)(this)).processAOI(inValue);
            return retVal.Body.processAOIReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiffCreate.RVS.processAOI2Response DiffCreate.RVS.RequestValidationService.processAOI2(DiffCreate.RVS.processAOI2Request request) {
            return base.Channel.processAOI2(request);
        }
        
        public string processAOI2(string requestInfoXml) {
            DiffCreate.RVS.processAOI2Request inValue = new DiffCreate.RVS.processAOI2Request();
            inValue.Body = new DiffCreate.RVS.processAOI2RequestBody();
            inValue.Body.requestInfoXml = requestInfoXml;
            DiffCreate.RVS.processAOI2Response retVal = ((DiffCreate.RVS.RequestValidationService)(this)).processAOI2(inValue);
            return retVal.Body.processAOI2Return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiffCreate.RVS.getTiledDataDirectURLsResponse DiffCreate.RVS.RequestValidationService.getTiledDataDirectURLs(DiffCreate.RVS.getTiledDataDirectURLsRequest request) {
            return base.Channel.getTiledDataDirectURLs(request);
        }
        
        public string getTiledDataDirectURLs(string requestInfoXml) {
            DiffCreate.RVS.getTiledDataDirectURLsRequest inValue = new DiffCreate.RVS.getTiledDataDirectURLsRequest();
            inValue.Body = new DiffCreate.RVS.getTiledDataDirectURLsRequestBody();
            inValue.Body.requestInfoXml = requestInfoXml;
            DiffCreate.RVS.getTiledDataDirectURLsResponse retVal = ((DiffCreate.RVS.RequestValidationService)(this)).getTiledDataDirectURLs(inValue);
            return retVal.Body.getTiledDataDirectURLsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiffCreate.RVS.getTiledDataDirectURLs2Response DiffCreate.RVS.RequestValidationService.getTiledDataDirectURLs2(DiffCreate.RVS.getTiledDataDirectURLs2Request request) {
            return base.Channel.getTiledDataDirectURLs2(request);
        }
        
        public string getTiledDataDirectURLs2(string requestInfoXml) {
            DiffCreate.RVS.getTiledDataDirectURLs2Request inValue = new DiffCreate.RVS.getTiledDataDirectURLs2Request();
            inValue.Body = new DiffCreate.RVS.getTiledDataDirectURLs2RequestBody();
            inValue.Body.requestInfoXml = requestInfoXml;
            DiffCreate.RVS.getTiledDataDirectURLs2Response retVal = ((DiffCreate.RVS.RequestValidationService)(this)).getTiledDataDirectURLs2(inValue);
            return retVal.Body.getTiledDataDirectURLs2Return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiffCreate.RVS.validateChunksResponse DiffCreate.RVS.RequestValidationService.validateChunks(DiffCreate.RVS.validateChunksRequest request) {
            return base.Channel.validateChunks(request);
        }
        
        public string validateChunks(string requestInfoXml) {
            DiffCreate.RVS.validateChunksRequest inValue = new DiffCreate.RVS.validateChunksRequest();
            inValue.Body = new DiffCreate.RVS.validateChunksRequestBody();
            inValue.Body.requestInfoXml = requestInfoXml;
            DiffCreate.RVS.validateChunksResponse retVal = ((DiffCreate.RVS.RequestValidationService)(this)).validateChunks(inValue);
            return retVal.Body.validateChunksReturn;
        }
    }
}
